= Welcome to the Aktualizr Docs!
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

This is the automatic start page for version *{page-component-version}* of Aktualizr.

Aktualizr is one of two documentation components in the OTA Connect Docs Demo.
The other docs component, OTA CE, can be accessed via the component selector menu (aka component drawer) at the bottom of the menu on the left side of the page.

== Page source

This page is sourced from the AsciiDoc file named [.path]_index.adoc_ that is located at [.path]_aktualizr/docs/modules/ROOT/pages_.

=== Why is this the home page of Aktualizr?

This page is automatically used as the start page of Aktualizr because it is stored in the ROOT module and named [.path]_index.adoc_.

=== Why is this the home page of the OTA Connect Docs Demo site?

This page is used as the home page for the new OTA Connect Docs demo because it is assigned as the site `start_page` in the Demo site's playbook file [.path]_site.yml_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in the ROOT module of the Aktualizr repo*, the xref syntax would be `\xref:index.adoc[]`.

To create a cross reference *to this page from a page in the OTA CE guide of the OTA CE repo*, the xref syntax would be `\xref:ROOT:index.adoc[]`.

=== Always target the latest version of this page

To create a cross reference *to the latest version of this page from a page in the OTA CE repo*, the xref syntax would be `\xref:aktualizr::index.adoc[]`.

=== Target a specific version of this page

To create a cross reference *to version 1.0 of this page from a page in the OTA CE repo*, the xref syntax would be `\xref:1.0@aktualizr::index.adoc[]`.
