= The Aktualizr Guide Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

This is version *{page-component-version}* of the Aktualizr Guide in the aktualizr repo.

== Page source

This page is sourced from [.path]_aktualizr/docs/modules/aktualizr-guide/pages/overview.adoc_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in the Aktualizr Guide*, the xref syntax would be `\xref:overview.adoc[]`.

To create a cross reference *to this page from a page in the ROOT module of the Aktualizr Guide*, the xref syntax would be `\xref:aktualizr-guide:overview.adoc[]`.

=== Always target the latest version of this page

To create a cross reference *to the latest version of this page from a page in the OTA Community Edition (separate component)*, the xref syntax would be `\xref:aktualizr:aktualizr-guide:overview.adoc[]`.

=== Target a specific version of this page

To create a cross reference *to version 1.0 of this page from a page in a page in the OTA Community Edition (separate component)*, the xref syntax would be `\xref:1.0@aktualizr:aktualizr-guide:overview.adoc[]`.
